#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Layer 0
	[0] = LAYOUT_split_3x5_2(
        // Top row
        KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P,
        // Middle row
        MT(MOD_LCTL, KC_A), MT(MOD_LALT, KC_S), MT(MOD_LGUI, KC_D), MT(MOD_LSFT, KC_F), KC_G, KC_H, MT(MOD_RSFT, KC_J), MT(MOD_RGUI, KC_K), MT(MOD_RALT, KC_L), MT(MOD_RCTL, KC_SEMICOLON),
        // Bottom row
        KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLSH,
        // Thumb keys
        OSL(2), OSL(1), KC_SPACE, OSM(MOD_LSFT)),

    // Layer 1
	[1] = LAYOUT_split_3x5_2(
        // Top row
        KC_GRAVE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BACKSLASH, KC_LEFT_BRACKET, KC_RIGHT_BRACKET, KC_MINUS, KC_EQUAL,
        // Middle row
        MT(MOD_LCTL, KC_1), MT(MOD_LALT, KC_2), MT(MOD_LGUI, KC_3), MT(MOD_LSFT, KC_4), KC_5, KC_6, MT(MOD_LSFT, KC_7), MT(MOD_LGUI, KC_8), MT(MOD_LALT, KC_9), MT(MOD_LCTL, KC_0),
        // Bottom row
        KC_EXCLAIM, KC_AT, KC_HASH, KC_DOLLAR, KC_PERCENT, KC_CIRCUMFLEX, KC_AMPERSAND, KC_ASTERISK, KC_LEFT_PAREN, KC_RIGHT_PAREN,
        // Thumb keys
        KC_TRNS, KC_TRNS, KC_ENTER, KC_BACKSPACE
    ),

    // Layer 2
    [2] = LAYOUT_split_3x5_2(
        // Top row
        KC_TILDE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PIPE, KC_LEFT_CURLY_BRACE, KC_RIGHT_CURLY_BRACE, KC_UNDERSCORE, KC_KP_PLUS,

        // Middle row
        KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_TRNS, MT(MOD_RSFT, KC_LEFT), MT(MOD_RGUI, KC_DOWN), MT(MOD_RALT, KC_UP), MT(MOD_RCTL, KC_RIGHT), KC_QUOTE,

        // Bottom row
        MEH(KC_1), MEH(KC_2), MEH(KC_3), MEH(KC_4), MEH(KC_5), MEH(KC_6), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

        // Thumb keys
        KC_TRNS, KC_TRNS, KC_TAB, KC_ESC)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


// Make the tapping term for home row modifier's option keys longer
// Because I keep accidentally triggering them
// Which causes me to type weird alternate characters
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case MT(MOD_LALT, KC_S):
            return TAPPING_TERM + 200;
        case MT(MOD_RALT, KC_L):
            return TAPPING_TERM + 200;
        default:
            return TAPPING_TERM;
    }
}
